export type Treatment = {
  slug: string;
  name: string;
  category: string;
  summary: string;
  what: string;
  who: string;
  steps: { title: string; body: string }[];
  recovery: string;
  duration: string;
  anesthesia: string;
  faq: { q: string; a: string }[];
};

export const categories = [
  {
    slug: "viso",
    name: "Chirurgia del viso",
    blurb: "Armonia dei tratti, senza mai perdere la tua identità.",
  },
  {
    slug: "seno",
    name: "Chirurgia del seno",
    blurb: "Proporzione e naturalezza, calibrate sul tuo corpo.",
  },
  {
    slug: "corpo",
    name: "Chirurgia del corpo",
    blurb: "Linee più definite, con un recupero seguito passo dopo passo.",
  },
  {
    slug: "medicina-estetica",
    name: "Medicina estetica",
    blurb: "Trattamenti non chirurgici, risultati misurati e reversibili.",
  },
] as const;

const step = (title: string, body: string) => ({ title, body });

export const treatments: Treatment[] = [
  {
    slug: "rinoplastica",
    name: "Rinoplastica",
    category: "viso",
    summary: "Riequilibrare il naso rispettando il carattere del volto.",
    what: "Intervento che modifica struttura ossea e cartilaginea del naso per migliorarne forma, proporzioni e — quando necessario — la respirazione.",
    who: "Indicata a chi percepisce una sproporzione tra naso e resto del volto, o convive con difficoltà respiratorie legate al setto.",
    steps: [
      step("Consulenza e simulazione", "Analisi del volto, ascolto delle aspettative e simulazione digitale del risultato."),
      step("Pianificazione chirurgica", "Esami preoperatori e definizione della tecnica: aperta o chiusa, strutturata o conservativa."),
      step("Intervento", "Durata media 90-150 minuti, in anestesia generale, con dimissione in giornata o dopo una notte."),
      step("Follow-up", "Rimozione del tutore dopo 7 giorni, controlli programmati a 1, 3, 6 e 12 mesi."),
    ],
    recovery: "Rientro alla vita sociale in 10-14 giorni. Edema residuo in progressiva riduzione fino a 12 mesi.",
    duration: "90-150 minuti",
    anesthesia: "Generale",
    faq: [
      { q: "Resteranno cicatrici visibili?", a: "Nella tecnica chiusa non ci sono cicatrici esterne. Nella tecnica aperta resta una cicatrice millimetrica alla base del naso, che diventa quasi impercettibile." },
      { q: "Quando vedrò il risultato definitivo?", a: "Il risultato è già leggibile dopo un mese, ma la definizione finale arriva tra i 9 e i 12 mesi." },
    ],
  },
  {
    slug: "blefaroplastica",
    name: "Blefaroplastica",
    category: "viso",
    summary: "Uno sguardo riposato, senza cambiare espressione.",
    what: "Rimodellamento della cute e del grasso delle palpebre superiori e/o inferiori per correggere pesantezza e borse.",
    who: "Indicata a chi ha palpebre cadenti, borse o un'espressione percepita come stanca anche da riposato.",
    steps: [
      step("Valutazione", "Studio della dinamica palpebrale e del rapporto con sopracciglio e zigomo."),
      step("Intervento", "45-90 minuti, in anestesia locale con sedazione."),
      step("Prime 72 ore", "Impacchi freddi e riposo. Gonfiore massimo in seconda giornata."),
      step("Controlli", "Rimozione punti a 5-7 giorni, controllo a 1 e 6 mesi."),
    ],
    recovery: "Ritorno al lavoro in 7 giorni, ecchimosi residue coperte con make-up.",
    duration: "45-90 minuti",
    anesthesia: "Locale con sedazione",
    faq: [
      { q: "Cambierà la forma dei miei occhi?", a: "No. L'obiettivo è alleggerire, non modificare la forma dello sguardo." },
    ],
  },
  {
    slug: "lifting-viso-collo",
    name: "Lifting viso e collo",
    category: "viso",
    summary: "Ridefinire il contorno, mantenendo i movimenti naturali.",
    what: "Riposizionamento dei tessuti profondi (SMAS) del terzo medio e inferiore del volto e del collo.",
    who: "Indicato in presenza di lassità cutanea, perdita del profilo mandibolare e rilassamento del collo.",
    steps: [
      step("Analisi dei volumi", "Distinguere ciò che è lassità da ciò che è perdita di volume."),
      step("Intervento", "3-4 ore, anestesia generale, una notte di ricovero."),
      step("Prima settimana", "Medicazione elastica, riposo e alimentazione morbida."),
      step("Ripresa", "Controlli settimanali per il primo mese."),
    ],
    recovery: "Vita sociale dopo 2-3 settimane. Risultato stabile a 3 mesi.",
    duration: "3-4 ore",
    anesthesia: "Generale",
    faq: [
      { q: "Avrò un aspetto 'tirato'?", a: "No, se si agisce sui piani profondi e non sulla sola pelle. È esattamente la differenza tra un lifting fatto bene e uno mal calibrato." },
    ],
  },
  {
    slug: "otoplastica",
    name: "Otoplastica",
    category: "viso",
    summary: "Riportare le orecchie in armonia con il profilo.",
    what: "Correzione delle orecchie prominenti tramite rimodellamento della cartilagine.",
    who: "Indicata dall'età scolare in poi, sia in età pediatrica sia adulta.",
    steps: [
      step("Valutazione", "Misurazione dell'angolo auricolo-cefalico."),
      step("Intervento", "60-90 minuti, anestesia locale negli adulti."),
      step("Fascia elastica", "Da indossare giorno e notte per 7 giorni, poi solo la notte per 3 settimane."),
      step("Controllo", "A 7 giorni e a 3 mesi."),
    ],
    recovery: "Ripresa immediata delle attività leggere.",
    duration: "60-90 minuti",
    anesthesia: "Locale",
    faq: [{ q: "È adatta ai bambini?", a: "Sì, generalmente dai 6-7 anni, quando la cartilagine ha completato gran parte dello sviluppo." }],
  },
  {
    slug: "mastoplastica-additiva",
    name: "Mastoplastica additiva",
    category: "seno",
    summary: "Volume proporzionato, scelto insieme prima dell'intervento.",
    what: "Aumento del volume mammario con protesi anatomiche o rotonde, o con lipofilling nei casi selezionati.",
    who: "Indicata a chi desidera più volume, maggiore simmetria o un ripristino dopo gravidanza e allattamento.",
    steps: [
      step("Scelta della protesi", "Misurazioni toraciche e prova con simulatore per definire volume e proiezione."),
      step("Intervento", "60-90 minuti, anestesia generale."),
      step("Prime settimane", "Reggiseno contenitivo per 30 giorni, stop attività fisica per 6 settimane."),
      step("Follow-up", "Controlli a 7 giorni, 1, 6 e 12 mesi, poi annuali."),
    ],
    recovery: "Rientro al lavoro sedentario in 5-7 giorni.",
    duration: "60-90 minuti",
    anesthesia: "Generale",
    faq: [
      { q: "Le protesi vanno sostituite?", a: "Non hanno una scadenza fissa, ma richiedono controlli periodici ed eventuale sostituzione nel corso della vita." },
      { q: "Potrò allattare?", a: "Nella grande maggioranza dei casi sì: le vie di accesso utilizzate preservano la ghiandola." },
    ],
  },
  {
    slug: "mastopessi",
    name: "Mastopessi",
    category: "seno",
    summary: "Risollevare senza necessariamente aumentare.",
    what: "Rimodellamento e riposizionamento del seno e del complesso areola-capezzolo.",
    who: "Indicata in caso di ptosi mammaria dopo dimagrimenti, gravidanze o per naturale evoluzione.",
    steps: [
      step("Valutazione del grado di ptosi", "Definisce il tipo di cicatrice necessaria."),
      step("Intervento", "2-3 ore, anestesia generale."),
      step("Recupero", "Guaina contenitiva per 4-6 settimane."),
      step("Controlli", "A 7 giorni, 1 e 6 mesi."),
    ],
    recovery: "Vita normale in 10-14 giorni.",
    duration: "2-3 ore",
    anesthesia: "Generale",
    faq: [{ q: "Le cicatrici si vedranno?", a: "Sono inevitabili ma pianificate lungo linee nascoste; maturano nell'arco di 12-18 mesi." }],
  },
  {
    slug: "riduzione-mammaria",
    name: "Riduzione mammaria",
    category: "seno",
    summary: "Alleggerire, con un beneficio spesso anche posturale.",
    what: "Riduzione del volume mammario con rimodellamento della forma.",
    who: "Indicata in caso di ipertrofia con dolore cervicale, dorsale o limitazioni funzionali.",
    steps: [
      step("Inquadramento clinico", "Spesso include valutazione senologica preoperatoria."),
      step("Intervento", "2,5-3,5 ore, anestesia generale."),
      step("Degenza", "Una notte di ricovero."),
      step("Controlli", "Settimanali per il primo mese."),
    ],
    recovery: "Ripresa graduale in 2-3 settimane.",
    duration: "2,5-3,5 ore",
    anesthesia: "Generale",
    faq: [{ q: "È un intervento solo estetico?", a: "Ha spesso una componente funzionale rilevante, che va documentata nella valutazione clinica." }],
  },
  {
    slug: "liposuzione",
    name: "Liposuzione",
    category: "corpo",
    summary: "Rimodellare gli accumuli localizzati, non dimagrire.",
    what: "Aspirazione del grasso localizzato tramite microcannule, con tecniche di rifinitura superficiale.",
    who: "Indicata a chi ha peso stabile e accumuli resistenti a dieta e attività fisica.",
    steps: [
      step("Mappatura", "Disegno preoperatorio delle aree in piedi."),
      step("Intervento", "60-180 minuti in base alle aree trattate."),
      step("Guaina elastica", "Da indossare per 4 settimane."),
      step("Linfodrenaggio", "Cicli consigliati dalla seconda settimana."),
    ],
    recovery: "Ripresa in 7-10 giorni, risultato definito a 3 mesi.",
    duration: "60-180 minuti",
    anesthesia: "Locale con sedazione o generale",
    faq: [{ q: "Il grasso può tornare?", a: "Le cellule rimosse non si riformano, ma quelle residue possono aumentare di volume con l'aumento di peso." }],
  },
  {
    slug: "addominoplastica",
    name: "Addominoplastica",
    category: "corpo",
    summary: "Ricostruire la parete addominale dopo gravidanze o forti dimagrimenti.",
    what: "Rimozione della cute in eccesso e riparazione della diastasi dei muscoli retti.",
    who: "Indicata in presenza di lassità cutanea addominale e diastasi documentata.",
    steps: [
      step("Valutazione", "Ecografia della parete addominale quando indicata."),
      step("Intervento", "2,5-4 ore, anestesia generale."),
      step("Degenza", "1-2 notti, con mobilizzazione precoce."),
      step("Recupero", "Guaina per 6 settimane, sport dopo 8-10 settimane."),
    ],
    recovery: "Vita d'ufficio dopo 3 settimane.",
    duration: "2,5-4 ore",
    anesthesia: "Generale",
    faq: [{ q: "La cicatrice sarà nascosta?", a: "È posizionata sotto la linea dell'intimo e concordata prima dell'intervento." }],
  },
  {
    slug: "body-contouring",
    name: "Body contouring",
    category: "corpo",
    summary: "Un percorso combinato dopo grandi dimagrimenti.",
    what: "Insieme di procedure (braccia, cosce, fianchi, addome) pianificate in più tempi chirurgici.",
    who: "Indicato dopo chirurgia bariatrica o dimagrimenti importanti con peso stabile da almeno 12 mesi.",
    steps: [
      step("Piano personalizzato", "Definizione delle priorità e della sequenza degli interventi."),
      step("Primo tempo chirurgico", "In genere il distretto con maggiore impatto funzionale."),
      step("Intervallo", "3-6 mesi tra un tempo e l'altro."),
      step("Consolidamento", "Follow-up nutrizionale e fisioterapico."),
    ],
    recovery: "Variabile in base ai distretti, 3-6 settimane per tempo chirurgico.",
    duration: "Variabile",
    anesthesia: "Generale",
    faq: [{ q: "Si può fare tutto in una volta?", a: "Raramente. Frazionare gli interventi riduce i rischi e migliora la qualità del risultato." }],
  },
  {
    slug: "botox",
    name: "Tossina botulinica",
    category: "medicina-estetica",
    summary: "Ammorbidire le rughe d'espressione mantenendo la mimica.",
    what: "Micro-iniezioni che riducono la contrazione dei muscoli responsabili delle rughe dinamiche.",
    who: "Indicata per rughe frontali, glabellari e perioculari.",
    steps: [
      step("Studio della mimica", "Fotografie dinamiche per calibrare le unità."),
      step("Trattamento", "10-15 minuti, senza anestesia."),
      step("Effetto", "Visibile in 3-5 giorni, pieno a 14 giorni."),
      step("Mantenimento", "Ogni 4-6 mesi."),
    ],
    recovery: "Nessun fermo. Evitare sport e posizione supina per 4 ore.",
    duration: "10-15 minuti",
    anesthesia: "Nessuna",
    faq: [{ q: "Avrò il viso immobile?", a: "No, se il dosaggio è calibrato. L'obiettivo è ridurre la ruga, non la mimica." }],
  },
  {
    slug: "filler",
    name: "Filler di acido ialuronico",
    category: "medicina-estetica",
    summary: "Restituire volume dove il tempo lo ha sottratto.",
    what: "Iniezione di acido ialuronico reticolato per ripristinare volumi e definire profili.",
    who: "Indicato per zigomi, solchi naso-genieni, labbra e profilo mandibolare.",
    steps: [
      step("Analisi dei volumi", "Valutazione del viso in tre dimensioni."),
      step("Trattamento", "20-30 minuti con anestesia topica."),
      step("Assestamento", "48-72 ore per il riassorbimento dell'edema."),
      step("Controllo", "A 2 settimane per eventuali ritocchi."),
    ],
    recovery: "Immediato, con possibili lievi lividi.",
    duration: "20-30 minuti",
    anesthesia: "Topica",
    faq: [{ q: "È reversibile?", a: "Sì, l'acido ialuronico può essere sciolto con ialuronidasi." }],
  },
  {
    slug: "biorivitalizzazione",
    name: "Biorivitalizzazione",
    category: "medicina-estetica",
    summary: "Qualità della pelle, prima ancora che volume.",
    what: "Micro-iniezioni di acido ialuronico non reticolato, vitamine e aminoacidi.",
    who: "Indicata per pelle disidratata, spenta o esposta a fumo e sole.",
    steps: [
      step("Valutazione cutanea", "Analisi di idratazione ed elasticità."),
      step("Ciclo iniziale", "3-4 sedute a distanza di 2-3 settimane."),
      step("Mantenimento", "1 seduta ogni 3-4 mesi."),
      step("Skincare", "Protocollo domiciliare personalizzato."),
    ],
    recovery: "Nessun fermo.",
    duration: "20 minuti",
    anesthesia: "Topica",
    faq: [{ q: "Da che età si può fare?", a: "In genere dai 30 anni, ma dipende dalla qualità cutanea più che dall'età anagrafica." }],
  },
  {
    slug: "fili-di-sospensione",
    name: "Fili di sospensione",
    category: "medicina-estetica",
    summary: "Un sostegno leggero, quando il lifting non serve ancora.",
    what: "Inserimento di fili riassorbibili che sostengono e stimolano il collagene.",
    who: "Indicato in caso di lassità iniziale del terzo medio e del profilo mandibolare.",
    steps: [
      step("Selezione del caso", "Il filo non sostituisce il lifting: la selezione è decisiva."),
      step("Trattamento", "40-60 minuti in anestesia locale."),
      step("Prime 2 settimane", "Evitare masticazione intensa e massaggi del viso."),
      step("Durata", "Effetto medio 12-18 mesi."),
    ],
    recovery: "3-5 giorni di lieve gonfiore.",
    duration: "40-60 minuti",
    anesthesia: "Locale",
    faq: [{ q: "Sostituisce il lifting?", a: "No. Su lassità avanzate il risultato sarebbe insoddisfacente e di breve durata." }],
  },
];

export const treatmentsByCategory = (slug: string) => treatments.filter((t) => t.category === slug);
export const getTreatment = (slug: string) => treatments.find((t) => t.slug === slug);
