/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IlDottoreRouteImport } from './routes/il-dottore'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as RisultatiRouteImport } from './routes/risultati'
import { Route as TestimonianzeRouteImport } from './routes/testimonianze'
import { Route as TrattamentiIndexRouteImport } from './routes/trattamenti.index'
import { Route as TrattamentiCategoriaIndexRouteImport } from './routes/trattamenti.$categoria.index'
import { Route as TrattamentiCategoriaSlugRouteImport } from './routes/trattamenti.$categoria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IlDottoreRoute = IlDottoreRouteImport.update({
  id: '/il-dottore',
  path: '/il-dottore',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const RisultatiRoute = RisultatiRouteImport.update({
  id: '/risultati',
  path: '/risultati',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonianzeRoute = TestimonianzeRouteImport.update({
  id: '/testimonianze',
  path: '/testimonianze',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiIndexRoute = TrattamentiIndexRouteImport.update({
  id: '/trattamenti/',
  path: '/trattamenti/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiCategoriaIndexRoute =
  TrattamentiCategoriaIndexRouteImport.update({
    id: '/trattamenti/$categoria/',
    path: '/trattamenti/$categoria/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrattamentiCategoriaSlugRoute =
  TrattamentiCategoriaSlugRouteImport.update({
    id: '/trattamenti/$categoria/$slug',
    path: '/trattamenti/$categoria/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/trattamenti/$categoria/': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/trattamenti': typeof TrattamentiIndexRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/trattamenti/$categoria': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/trattamenti/$categoria/': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/trattamenti/'
    | '/trattamenti/$categoria/$slug'
    | '/trattamenti/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/trattamenti'
    | '/trattamenti/$categoria/$slug'
    | '/trattamenti/$categoria'
  id:
    | '__root__'
    | '/'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/trattamenti/'
    | '/trattamenti/$categoria/$slug'
    | '/trattamenti/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IlDottoreRoute: typeof IlDottoreRoute
  MagazineRoute: typeof MagazineRoute
  RisultatiRoute: typeof RisultatiRoute
  TestimonianzeRoute: typeof TestimonianzeRoute
  TrattamentiIndexRoute: typeof TrattamentiIndexRoute
  TrattamentiCategoriaSlugRoute: typeof TrattamentiCategoriaSlugRoute
  TrattamentiCategoriaIndexRoute: typeof TrattamentiCategoriaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/il-dottore': {
      id: '/il-dottore'
      path: '/il-dottore'
      fullPath: '/il-dottore'
      preLoaderRoute: typeof IlDottoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risultati': {
      id: '/risultati'
      path: '/risultati'
      fullPath: '/risultati'
      preLoaderRoute: typeof RisultatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonianze': {
      id: '/testimonianze'
      path: '/testimonianze'
      fullPath: '/testimonianze'
      preLoaderRoute: typeof TestimonianzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/': {
      id: '/trattamenti/'
      path: '/trattamenti'
      fullPath: '/trattamenti/'
      preLoaderRoute: typeof TrattamentiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/$categoria/': {
      id: '/trattamenti/$categoria/'
      path: '/trattamenti/$categoria'
      fullPath: '/trattamenti/$categoria/'
      preLoaderRoute: typeof TrattamentiCategoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/$categoria/$slug': {
      id: '/trattamenti/$categoria/$slug'
      path: '/trattamenti/$categoria/$slug'
      fullPath: '/trattamenti/$categoria/$slug'
      preLoaderRoute: typeof TrattamentiCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IlDottoreRoute: IlDottoreRoute,
  MagazineRoute: MagazineRoute,
  RisultatiRoute: RisultatiRoute,
  TestimonianzeRoute: TestimonianzeRoute,
  TrattamentiIndexRoute: TrattamentiIndexRoute,
  TrattamentiCategoriaSlugRoute: TrattamentiCategoriaSlugRoute,
  TrattamentiCategoriaIndexRoute: TrattamentiCategoriaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
