/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as IlDottoreRouteImport } from './routes/il-dottore'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as RisultatiRouteImport } from './routes/risultati'
import { Route as TestimonianzeRouteImport } from './routes/testimonianze'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LegaleCookieRouteImport } from './routes/legale.cookie'
import { Route as LegaleDatiSanitariRouteImport } from './routes/legale.dati-sanitari'
import { Route as LegaleDirittiRouteImport } from './routes/legale.diritti'
import { Route as LegalePrivacyRouteImport } from './routes/legale.privacy'
import { Route as LegaleTerminiRouteImport } from './routes/legale.termini'
import { Route as TrattamentiIndexRouteImport } from './routes/trattamenti.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminLeadRouteImport } from './routes/_authenticated/admin.lead'
import { Route as TrattamentiCategoriaIndexRouteImport } from './routes/trattamenti.$categoria.index'
import { Route as TrattamentiCategoriaSlugRouteImport } from './routes/trattamenti.$categoria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const IlDottoreRoute = IlDottoreRouteImport.update({
  id: '/il-dottore',
  path: '/il-dottore',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const RisultatiRoute = RisultatiRouteImport.update({
  id: '/risultati',
  path: '/risultati',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonianzeRoute = TestimonianzeRouteImport.update({
  id: '/testimonianze',
  path: '/testimonianze',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegaleCookieRoute = LegaleCookieRouteImport.update({
  id: '/legale/cookie',
  path: '/legale/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const LegaleDatiSanitariRoute = LegaleDatiSanitariRouteImport.update({
  id: '/legale/dati-sanitari',
  path: '/legale/dati-sanitari',
  getParentRoute: () => rootRouteImport,
} as any)
const LegaleDirittiRoute = LegaleDirittiRouteImport.update({
  id: '/legale/diritti',
  path: '/legale/diritti',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalePrivacyRoute = LegalePrivacyRouteImport.update({
  id: '/legale/privacy',
  path: '/legale/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegaleTerminiRoute = LegaleTerminiRouteImport.update({
  id: '/legale/termini',
  path: '/legale/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiIndexRoute = TrattamentiIndexRouteImport.update({
  id: '/trattamenti/',
  path: '/trattamenti/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadRoute = AuthenticatedAdminLeadRouteImport.update({
  id: '/lead',
  path: '/lead',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const TrattamentiCategoriaIndexRoute =
  TrattamentiCategoriaIndexRouteImport.update({
    id: '/trattamenti/$categoria/',
    path: '/trattamenti/$categoria/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrattamentiCategoriaSlugRoute =
  TrattamentiCategoriaSlugRouteImport.update({
    id: '/trattamenti/$categoria/$slug',
    path: '/trattamenti/$categoria/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contatti': typeof ContattiRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/legale/cookie': typeof LegaleCookieRoute
  '/legale/dati-sanitari': typeof LegaleDatiSanitariRoute
  '/legale/diritti': typeof LegaleDirittiRoute
  '/legale/privacy': typeof LegalePrivacyRoute
  '/legale/termini': typeof LegaleTerminiRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
  '/admin/lead': typeof AuthenticatedAdminLeadRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/trattamenti/$categoria/': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contatti': typeof ContattiRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/legale/cookie': typeof LegaleCookieRoute
  '/legale/dati-sanitari': typeof LegaleDatiSanitariRoute
  '/legale/diritti': typeof LegaleDirittiRoute
  '/legale/privacy': typeof LegalePrivacyRoute
  '/legale/termini': typeof LegaleTerminiRoute
  '/trattamenti': typeof TrattamentiIndexRoute
  '/admin/lead': typeof AuthenticatedAdminLeadRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/trattamenti/$categoria': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contatti': typeof ContattiRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/legale/cookie': typeof LegaleCookieRoute
  '/legale/dati-sanitari': typeof LegaleDatiSanitariRoute
  '/legale/diritti': typeof LegaleDirittiRoute
  '/legale/privacy': typeof LegalePrivacyRoute
  '/legale/termini': typeof LegaleTerminiRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
  '/_authenticated/admin/lead': typeof AuthenticatedAdminLeadRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/trattamenti/$categoria/': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contatti'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/admin'
    | '/legale/cookie'
    | '/legale/dati-sanitari'
    | '/legale/diritti'
    | '/legale/privacy'
    | '/legale/termini'
    | '/trattamenti/'
    | '/admin/lead'
    | '/trattamenti/$categoria/$slug'
    | '/admin/'
    | '/trattamenti/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contatti'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/legale/cookie'
    | '/legale/dati-sanitari'
    | '/legale/diritti'
    | '/legale/privacy'
    | '/legale/termini'
    | '/trattamenti'
    | '/admin/lead'
    | '/trattamenti/$categoria/$slug'
    | '/admin'
    | '/trattamenti/$categoria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contatti'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/_authenticated/admin'
    | '/legale/cookie'
    | '/legale/dati-sanitari'
    | '/legale/diritti'
    | '/legale/privacy'
    | '/legale/termini'
    | '/trattamenti/'
    | '/_authenticated/admin/lead'
    | '/trattamenti/$categoria/$slug'
    | '/_authenticated/admin/'
    | '/trattamenti/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContattiRoute: typeof ContattiRoute
  IlDottoreRoute: typeof IlDottoreRoute
  MagazineRoute: typeof MagazineRoute
  RisultatiRoute: typeof RisultatiRoute
  TestimonianzeRoute: typeof TestimonianzeRoute
  LegaleCookieRoute: typeof LegaleCookieRoute
  LegaleDatiSanitariRoute: typeof LegaleDatiSanitariRoute
  LegaleDirittiRoute: typeof LegaleDirittiRoute
  LegalePrivacyRoute: typeof LegalePrivacyRoute
  LegaleTerminiRoute: typeof LegaleTerminiRoute
  TrattamentiIndexRoute: typeof TrattamentiIndexRoute
  TrattamentiCategoriaSlugRoute: typeof TrattamentiCategoriaSlugRoute
  TrattamentiCategoriaIndexRoute: typeof TrattamentiCategoriaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/il-dottore': {
      id: '/il-dottore'
      path: '/il-dottore'
      fullPath: '/il-dottore'
      preLoaderRoute: typeof IlDottoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risultati': {
      id: '/risultati'
      path: '/risultati'
      fullPath: '/risultati'
      preLoaderRoute: typeof RisultatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonianze': {
      id: '/testimonianze'
      path: '/testimonianze'
      fullPath: '/testimonianze'
      preLoaderRoute: typeof TestimonianzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legale/cookie': {
      id: '/legale/cookie'
      path: '/legale/cookie'
      fullPath: '/legale/cookie'
      preLoaderRoute: typeof LegaleCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/dati-sanitari': {
      id: '/legale/dati-sanitari'
      path: '/legale/dati-sanitari'
      fullPath: '/legale/dati-sanitari'
      preLoaderRoute: typeof LegaleDatiSanitariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/diritti': {
      id: '/legale/diritti'
      path: '/legale/diritti'
      fullPath: '/legale/diritti'
      preLoaderRoute: typeof LegaleDirittiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/privacy': {
      id: '/legale/privacy'
      path: '/legale/privacy'
      fullPath: '/legale/privacy'
      preLoaderRoute: typeof LegalePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/termini': {
      id: '/legale/termini'
      path: '/legale/termini'
      fullPath: '/legale/termini'
      preLoaderRoute: typeof LegaleTerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/': {
      id: '/trattamenti/'
      path: '/trattamenti'
      fullPath: '/trattamenti/'
      preLoaderRoute: typeof TrattamentiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lead': {
      id: '/_authenticated/admin/lead'
      path: '/lead'
      fullPath: '/admin/lead'
      preLoaderRoute: typeof AuthenticatedAdminLeadRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/trattamenti/$categoria/': {
      id: '/trattamenti/$categoria/'
      path: '/trattamenti/$categoria'
      fullPath: '/trattamenti/$categoria/'
      preLoaderRoute: typeof TrattamentiCategoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/$categoria/$slug': {
      id: '/trattamenti/$categoria/$slug'
      path: '/trattamenti/$categoria/$slug'
      fullPath: '/trattamenti/$categoria/$slug'
      preLoaderRoute: typeof TrattamentiCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLeadRoute: typeof AuthenticatedAdminLeadRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLeadRoute: AuthenticatedAdminLeadRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContattiRoute: ContattiRoute,
  IlDottoreRoute: IlDottoreRoute,
  MagazineRoute: MagazineRoute,
  RisultatiRoute: RisultatiRoute,
  TestimonianzeRoute: TestimonianzeRoute,
  LegaleCookieRoute: LegaleCookieRoute,
  LegaleDatiSanitariRoute: LegaleDatiSanitariRoute,
  LegaleDirittiRoute: LegaleDirittiRoute,
  LegalePrivacyRoute: LegalePrivacyRoute,
  LegaleTerminiRoute: LegaleTerminiRoute,
  TrattamentiIndexRoute: TrattamentiIndexRoute,
  TrattamentiCategoriaSlugRoute: TrattamentiCategoriaSlugRoute,
  TrattamentiCategoriaIndexRoute: TrattamentiCategoriaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
